{
  "artifacts": [
    "densenet169.medical.transfer.medico.w.reg.json",
    "medico.json"
  ],
  "command": "wrapper",
  "experiment": {
    "base_dir": "/home/steven/Github/keras-training-system/src",
    "dependencies": [
      "Keras==2.2.2",
      "numpy==1.14.5",
      "sacred==0.7.4",
      "tensorflow-gpu==1.10.1"
    ],
    "mainfile": "run.py",
    "name": "densenet169_medical_transfer_medico_with_regularization",
    "repositories": [],
    "sources": [
      [
        "evaluate.py",
        "_sources/evaluate_74c7f16e5de658974ec7ef4989a9bfcb.py"
      ],
      [
        "run.py",
        "_sources/run_4195f7731ab921bc8074777c8e02c7a1.py"
      ],
      [
        "train.py",
        "_sources/train_b71b8299b0737b8ca7f652ac8d3f5619.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_0d548108773d28bfbd74bea8c9a0350e.py"
      ],
      [
        "utils/util.py",
        "_sources/util_3f3726bd2138527c730f11d16fd8703e.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/steven/anaconda3/envs/py36/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"run.py\", line 177, in wrapper\n    run( config, config_path )\n",
    "  File \"run.py\", line 90, in run\n    model = model_builder.build(config)\n",
    "  File \"/home/steven/Github/keras-training-system/src/models/densenet169_medical_with_reg.py\", line 15, in build\n    base_model = load_model(model_file)\n",
    "  File \"/home/steven/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/saving.py\", line 249, in load_model\n    f = h5py.File(filepath, mode='r')\n",
    "  File \"/home/steven/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/_hl/files.py\", line 269, in __init__\n    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)\n",
    "  File \"/home/steven/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/_hl/files.py\", line 99, in make_fid\n    fid = h5f.open(name, flags, fapl=fapl)\n",
    "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
    "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
    "  File \"h5py/h5f.pyx\", line 78, in h5py.h5f.open\n",
    "OSError: Unable to open file (unable to open file: name = '/home/steven/Models/densenet169_medical_combo_model_85_val_acc.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n"
  ],
  "heartbeat": "2018-09-17T12:30:14.430655",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz",
    "gpus": {
      "driver_version": "390.87",
      "gpus": [
        {
          "model": "GeForce GTX 980",
          "persistence_mode": false,
          "total_memory": 4041
        }
      ]
    },
    "hostname": "steven-Aurora-R3",
    "os": [
      "Linux",
      "Linux-4.15.0-34-generic-x86_64-with-debian-buster-sid"
    ],
    "python_version": "3.6.5"
  },
  "meta": {
    "command": "wrapper",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2018-09-17T12:29:59.727289",
  "status": "FAILED",
  "stop_time": "2018-09-17T12:30:14.432580"
}